### ISSUE TITLE
MAKE A WIKI- Maybe get with Jeff and add his content?

### ISSUE THREAD

**Issue by ph8tel** [rpt09-studyhall/notesWiki#1]
MAKE THIS WORK
~3 sprint points

**Comment by ph8tel** [comment]
@ryanbrennan12 It is as easy as clicking on the wiki tab, then create page.

**Comment by ph8tel** [comment]
@McCloudFace Maybe you could transfer some info here?

**Comment by McCloudFace** [comment]
I'd be happy to move my scribbles into this repo. They certainly aren't helping me, but maybe they'll help someone else.

**Comment by rybrennan** [comment]
Jeff does have the best notes, fur sho
